name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  actions: read
  contents: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee #4.0.1
        with:
          dotnet-version: 6.x

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #4.1.7

      - name: Build
        run: dotnet build --configuration Release

      - name: Prepare release notes
        id: release_notes
        shell: bash
        run: |
          tags=$(awk '/^v.*/ {print}' ./RELEASE-NOTES.md)
          tags_array=($tags)
          len=${#tags_array[@]}
          echo "release_tag=${tags_array[0]}" >> $GITHUB_OUTPUT
          if [ ${len} -ge 2 ]
          then
            prev_tag=${tags_array[1]};
            notes=$(awk "BEGIN{ found=1 } /$prev_tag/{found=0}  {if (found) print }" ./RELEASE-NOTES.md)
            echo "${notes}" > ./RELEASE-NOTES.md
            echo "" >> ./RELEASE-NOTES.md
            echo "**Full Changelog**: https://github.com/luzmane/emby.kinopoisk.ru/compare/${tags_array[1]}...${tags_array[0]}" >> ./RELEASE-NOTES.md
          fi

      - name: Create release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # 2.0.8
        with:
          files: ./EmbyKinopoiskRu/bin/Release/*/EmbyKinopoiskRu.dll
          body_path: ./RELEASE-NOTES.md
          fail_on_unmatched_files: true
          name: "EmbyKinopoiskRu ${{ steps.release_notes.outputs.release_tag }}"
          tag_name: "${{ steps.release_notes.outputs.release_tag }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
